rm(list=ls())
setwd("E:/Analytics/Dutyfree sales data")
dfjuly= read.csv("July-2018.csv",header = T)
dfjuly[,22] <- as.numeric(as.character(dfjuly[,22]))
##################market basket analysis##################################################
arrival<-subset(dfjuly,dfjuly$Location=="Arrival")
departure<-subset(dfjuly,dfjuly$Location=="Departure")
Boutiques<-subset(dfjuly,dfjuly$Location=="Speciality")
library("arules")
library("arulesViz")
t<-split(as.character(common$Item.Description),as.character(common$Passport.No.))
txn <- as(t, "transactions")
basket_rules<-apriori(txn, parameter = list(sup = 0.001, conf = 0.001, target="rules"))
write.csv(as(basket_rules, "data.frame"),"dep1.csv")
basket_rules<-as(basket_rules, "data.frame")
plot(head(sort(basket_rules, by="lift"), 10), method="graph", control=list(type="itemsets"),main="Sale Visualisation")
